# Generated by Django 2.2.19 on 2022-06-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220618_0307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribtion',
            new_name='Subscription',
        ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_subsrcibtion',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'subscribed'), name='unique_subsrciption'),
        ),
    ]
